apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-c4mijajisupwh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-c4mijajisupwh
    app.kubernetes.io/part-of: test-gitlabrenovate-dx9qm3p9p5btc
  name: component-c4mijajisupwh
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-c4mijajisupwh
status:
  loadBalancer: {}
